server:
  servlet:
   context-path: /mcs-registro-sospechoso/

spring:
  aop:
    proxy-target-class: true

logging:
  config: /opt/data/mcs-minsa/log/mcs-registro-sospechoso/config/log4j2-mcs-registro-sospechoso.xml